name: Discord Notification

on:
  workflow_run:
    workflows: ["Dockerized"]
    types: [completed]

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      - name: Push the notification using Discord webhook
        env:
          # 🟢 has poor compatibility: https://www.unicompat.com/1F7E2
          CI_STATUS: ${{ github.event.workflow_run.conclusion == 'success' && '✅' ||  github.event.workflow_run.conclusion == 'failure' && '🔴' || github.event.workflow_run.conclusion }}
          REPO_NAME: ${{ github.event.repository.name }}
          GIT_BRANCH: ${{ github.event.workflow_run.head_branch }}
          WORKFLOW_NAME: ${{ github.event.workflow_run.name }}
          WORKFLOW_URL: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.html_url || '' }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl \
            -i \
            -H "Content-Type:application/json" \
            -X POST \
            --data "{\"content\":\"$CI_STATUS **$REPO_NAME** > $WORKFLOW_NAME $WORKFLOW_URL\"}" \
            $DISCORD_WEBHOOK